{"errorMessage": "'sourceIp'", "errorType": "KeyError", "requestId": "d183ea8b-f8f6-4de3-946c-7620e5ffbdef", "stackTrace": ["  File \"/var/lang/lib/python3.12/site-packages/mangum/adapter.py\", line 63, in __call__\n    scope = handler.scope\n", "  File \"/var/lang/lib/python3.12/site-packages/mangum/handlers/api_gateway.py\", line 150, in scope\n    source_ip = request_context[\"http\"][\"sourceIp\"]\n"]}